apiVersion: v1
kind: Pod
metadata:
  name: dummy-proxy-pod
  namespace: v6-jobs
  labels:
    app: dummy-v6-proxy
spec:
  hostname: v6proxy
  subdomain: k8snet
  containers:
  - name: dummy-v6-proxy
    tty: true
    image: hectorcadavid/dummy-v6-server-proxy
    ports:
    - containerPort:  8080
